---
deployment:
  tasks:
    - chmod -R 755 /home2/bulutist/repositories/bulutistihbarat/storage
    - chmod -R 755 /home2/bulutist/repositories/bulutistihbarat/bootstrap/cache
    - cp -n /home2/bulutist/repositories/bulutistihbarat/.env.example /home2/bulutist/repositories/bulutistihbarat/.env
    - cp /home2/bulutist/repositories/bulutistihbarat/public_html.htaccess /home2/bulutist/public_html/.htaccess
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/composer.phar install --no-dev --no-scripts --optimize-autoloader --working-dir=/home2/bulutist/repositories/bulutistihbarat
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan key:generate --force
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan config:clear
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan cache:clear
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan route:clear
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan view:clear
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan migrate --force
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan storage:link --force
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan optimize
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/composer.phar install --no-dev --no-scripts --optimize-autoloader --working-dir=/home2/bulutist/repositories/bulutistihbarat
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan key:generate --force
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan config:clear
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan cache:clear
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan route:clear
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan view:clear
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan migrate --force
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan storage:link --force
    - /usr/local/bin/php /home2/bulutist/repositories/bulutistihbarat/artisan optimize
